# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload CSV to Spreadsheet
        if: github.event_name == 'sheet' && startsWith(github.event.ref, 'refs/tags')
        uses: canonical-web-and-design/csv-to-google-spreadsheet
        with:
          csv_path: public/languages.csv
          spreadsheet_id: ${{ secrets.google_spreadsheet_id }}
          worksheet: 0
          google_service_account_email: ${{ secrets.google_service_account_email }}
          google_service_account_private_key: ${{ secrets.google_service_account_private_key }}
